# Generated by Django 4.2.7 on 2023-11-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_depositoptions_rsrv_type_depositoptions_rsrv_type_nm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositoptions',
            name='rsrv_type',
        ),
        migrations.RemoveField(
            model_name='depositoptions',
            name='rsrv_type_nm',
        ),
    ]
