# Generated by Django 4.2.7 on 2023-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='password',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
