# Generated by Django 4.2.7 on 2023-11-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_financial_products_dep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite',
        ),
        migrations.AddField(
            model_name='favorite',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='title',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
