# Generated by Django 4.2.7 on 2023-11-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_depositoptions_rsrv_type_and_more'),
        ('accounts', '0004_alter_user_money_alter_user_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='financial_products_dep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='financial_products_sav',
        ),
        migrations.AddField(
            model_name='user',
            name='financial_options_dep',
            field=models.ManyToManyField(related_name='dep_users', to='products.depositoptions'),
        ),
        migrations.AddField(
            model_name='user',
            name='financial_options_sav',
            field=models.ManyToManyField(related_name='sav_users', to='products.savingoptions'),
        ),
    ]
